source/routes/web.php
Route::get('export/ajax/kelas/{category}/{major?}','RekapController@ajaxKelas')->name('rekap.ajax.kelas');

Route::get('laporan_bos','RekapController@ulala');
/**
 * Route Simpanan
 */
 Route::get('simpanan', 'SimpananController@index')->name('simpanan')->middleware('cekstatus');
 Route::post('simpanan/filter', 'SimpananController@filter')->name('simpanan.filter')->middleware('cekstatus');

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/rekap_Pemasukan', 'MenuRekapController@indexPemasukan')->name('rekap.pemasukan');
Route::get('/rekap_Pengeluaran', 'MenuRekapController@indexPengeluaran')->name('rekap.pengeluaran');
Route::get('/rekap_bukbes', 'MenuRekapController@indexBB')->name('rekap.bukbes');
Route::get('/rekap_tunggakan/{stat?}', 'MenuRekapController@indexTunggakan')->name('rekap.tunggakan');

Route::post('/rekap_Pemasukan', 'MenuRekapController@indexPemasukanFilter')->name('rekap.pemasukan.filter');
Route::post('/rekap_Pengeluaran', 'MenuRekapController@indexPengeluaranFilter')->name('rekap.pengeluaran.filter');
Route::post('/rekap_bukbes', 'MenuRekapController@indexBukuBesarFilter')->name('rekap.bukbes.filter');
Route::post('/rekap_tunggakan/{stat?}', 'MenuRekapController@indexTunggakanFilter')->name('rekap.tunggakan.filter');

Route::get('/rekap_Pemasukan/ajax/{stat}', 'MenuRekapController@ajaxPemasukan')->name('rekap.pemasukan.ajax');
Route::get('/rekap_Pengeluaran/ajax/{stat}', 'MenuRekapController@ajaxPengeluaran')->name('rekap.pengeluaran.ajax');
Route::get('/rekap_bukbes/ajax/{stat}', 'MenuRekapController@ajaxBukuBesar')->name('rekap.bukbes.ajax');
Route::get('/rekap_tunggakan/ajax/{stat?}/{filter?}', 'MenuRekapController@ajaxTunggakan')->name('rekap.tunggakan.ajax');
Route::get('/rekap_tunggakan/ajax/{id_siswa}', 'MenuRekapController@ajaxTunggakanSiswa')->name('rekap.tunggakan.ajax.siswa');
Route::get('/rekap_tunggakan/_ajax/data/{keyword?}', 'MenuRekapController@ajaxTunggakanView')->name('rekap.tunggakan.ajax.view');
Route::get('/rekap_tunggakan/_ajax_kategori/data/{keyword?}', 'MenuRekapController@ajaxTunggakanKategoriView')->name('rekap.tunggakan.ajax.view');
Route::get('/rekap_tunggakan/data_master/{stat?}', 'MenuRekapController@ajaxTunggakanMaster')->name('rekap.tunggakan.ajax.master');

Route::post('/rekap_Pemasukan/export', 'MenuRekapController@pemasukan')->name('rekap.pemasukan.export');
Route::get('/rekap_Pemasukan/data_master', 'MenuRekapController@ajaxPemasukanMaster')->name('rekap.pemasukan.ajax.master');
Route::get('/rekap_Pemasukan/total', 'MenuRekapController@ajaxPemasukanTotal')->name('rekap.pemasukan.ajax.total');
Route::post('/rekap_Pengeluaran/export', 'MenuRekapController@pengeluaran')->name('rekap.pengeluaran.export');
Route::post('/rekap_bukbes/export', 'MenuRekapController@bukuBesar')->name('rekap.bukbes.export');
Route::post('/rekap_tunggakan_export', 'MenuRekapController@tunggakan')->name('rekap.tunggakan.export');

Route::get('penyesuaian', 'PenyesuaianController@index');
Route::get('penyesuaian/ajax', 'PenyesuaianController@ajax');

Route::get('data_rekap_tunggakan/{stat?}', 'MenuRekapController@ajaxTunggakanMasterSiswa')->name('data.rekap.tunggakan');


// setting biaya
Route::put('setting_biaya/update/{id}', 'SettingBiayaController@updates')->name('setting_biaya.updates')->middleware('cekstatus');
Route::resource('setting_biaya', 'SettingBiayaController');

/**


 * controlling
 */

Route::resource('/backpemasukan', 'BackPemasukanController');
Route::post('backpemasukan/filter', 'BackPemasukanController@filter')->name('backpemasukan.filter');

Route::resource('/backpengeluaran', 'BackPengeluaranController');
Route::post('backpengeluaran/filter', 'BackPengeluaranController@filter')->name('backpengeluaran.filter');
Route::get('/backpembayaran/history/{id}', 'BackPembayaranController@history')->name('backpembayaran.history');
Route::resource('/backpembayaran', 'BackPembayaranController');

Route::delete('backpembayaran/destroy2/{id}', 'BackPembayaranController@destroy2')->name('backpembayaran.destroy2');

Route::get('backpembayaran/detail/{id}', 'BackPembayaranController@detailBackPembayaran')->name('backpembayaran.detail');
Route::get('backpembayaran/detail2/{id}/{kategori_pembayaran}', 'BackPembayaranController@detailBackPembayaran2')->name('backpembayaran.detail2');

// use App\PaymentDetail;
use App\Payment;
use App\Student;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
Route::get('siswa-request/tunggakan', function(Request $request){
    $uname = $request->uname;
    $key = $request->key;
    if ($uname != "" && $key != "") {
        $data = Student::where('uname', $uname)->where('key', $key)->count();
        if ($data == 1) {
            $siswa = Student::where('uname', $uname)->where('key', $key)->first();
            $data = Payment::addSelect(DB::raw("
                students.id as student_id,
                payments.id as id,
                students.angkatan_id,
                financing_categories.id as financing_category_id,
                financing_categories.jenis
                "))
                ->join('students', 'students.id', '=', 'payments.student_id')
                ->join('angkatans', 'angkatans.id', '=', 'students.angkatan_id')
                ->join('financing_categories', 'financing_categories.id', '=', 'payments.financing_category_id')
                ->orderBy('financing_categories.nama', 'asc')
                ->where('payments.status_lunas', 0)
                ->where('students.id', $siswa->id)
                ->get();
            $no = 1;
            $title = "Laporan Tunggakan " . $siswa->nama;
            return view('export.rekap_tunggakan_kategori_siswa', compact('no','title','data'));
        } else { 
            Session::flash('error', 'Uname atau Key salah!');
            return redirect('siswa-request/tunggakan');
        }
    } else {
        return view('SiswaRequest');
    }
});
use App\Http\Controllers\PerhitunganTunggakanSiswaController;
Route::get('siswa-request/tunggakan-cek', function(Request $request){
    $p = new PerhitunganTunggakanSiswaController();
    return $p->kategori(16);
});

Route::get('penyesuaian/data', function(){
    $data = Student::all();
    echo "<pre>";
    foreach ($data as $key => $value) {
        $temp = explode(" ", $value['nama']);
        $uname = join("_",$temp);
        $uname .= "_" . $value['id'];
        $uname = strtolower($uname);
        $key = Str::random(6);
        print_r($uname);
        print_r($key);
        echo "<hr>";
    }
    die;
    $data = Payment::chunk(100, function($payments){
                foreach ($payments as $key => $v) {
                    // dd($value);
                    if ($v->category->jenis == "Bayar per Bulan") {
                        $kelas_x = $v->detail[0]->periode->kelas_x;
                        $kelas_xi = $v->detail[0]->periode->kelas_xi;
                        $kelas_xii = $v->detail[0]->periode->kelas_xii;
                        $besaran = $kelas_x*12 + $kelas_xi*12 + $kelas_xii*12;
                        $potongan = 0;
                        $terbayar = $v->detail->sum('nominal');
                    }
                    else
                    {
                        // echo "<pre>";
                        // var_dump($v->student->nama);die;
                        $besaran = $v->detail[0]->periode->nominal;
                        if ( $v->jenis_potongan == "persentase")
                        {
                            $potongan = (intval($v->persentase) / 100) * $besaran;
                        }
                        else
                        {
                            $potongan = intval($v->nominal_potongan);
                        }
                        $terbayar = $v->detail[0]->cicilan->sum('nominal');
                    }
                    $sisa = $besaran - ($potongan + $terbayar);
                    if ($besaran !== 0 && $sisa == 0) {
                        $v->status_lunas = true;
                        $v->save();
                    } else {
                        $v->status_lunas = false;
                        $v->save();
                    }
                }
            });
    echo "<pre>";
    echo "DONE";
    // var_dump($data[0]);
    die;
});

use Illuminate\Support\Facades\DB;
Route::get('penyesuaian/print', function() {
    $title = "Laporan Tunggakan";
    $datas = DB::table('payment_details')
            ->select(DB::raw('students.nama as nama_murid,
            financing_categories.nama,
	financing_categories.id as financing_category_id,
	financing_categories.jenis as jenis_kategori,
            payment_details.id, 
            payment_details.payment_id,
            payment_details.payment_periode_id,
            angkatans.id as angkatan_id,
            majors.id as major_id,
            students.kelas,
            angkatans.angkatan,
            angkatans.tahun as tahun_angkatan,
            majors.inisial as inisial,
            majors.nama as jurusan, 
            count(payment_details.status) as banyak_tunggakan,
            financing_periodes.nominal,
            financing_periodes.kelas_x,
            financing_periodes.kelas_xi,
            financing_periodes.kelas_xii,
            getNominalCicilan(payment_details.id) as cicilan_dibayar,
            payments.jenis_pembayaran,
            payments.persentase,
            payments.nominal_potongan,
		payments.jenis_potongan,
	sum(payment_details.nominal) as nominal_detail,
	sum(cicilans.nominal) as nominal_cicilan,
            payment_details.status'))
            ->join('payments', 'payments.id', '=', 'payment_details.payment_id')
            ->join('financing_periodes', 'financing_periodes.id', '=', 'payment_details.payment_periode_id')
            ->join('financing_categories', 'financing_categories.id', '=', 'payments.financing_category_id')
            ->join('students', 'students.id', '=', 'payments.student_id')

source/app/BackPengeluaran.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class BackPengeluaran extends Model
{
    /**
     * Nama table yang digunakan
     */
    protected $table = 'back_pengeluaran';

    /**
     * Kolom yang dapat di isi
     */
    protected $fillable = [
        "title",
        "description",
        "sumber",
        "foto",
        "nominal",
        "tipe",
        "user",
        "keterangan",
        "created_at",
        "updated_at",

    ];
}

source/app/Http/Controllers/BackPengeluaranController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\BackPengeluaran;
use App\Expense;


class BackPengeluaranController extends Controller
{
     public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $datas = BackPengeluaran::orderBy('updated_at', 'desc')->get();
        $no=1;
        $bulan = BackPengeluaran::selectRaw('MONTH(created_at) AS bulan')
                ->groupBy('bulan')
                ->orderBy('bulan')
                ->get();
        $tahun = BackPengeluaran::selectRaw('YEAR(created_at) AS tahun')
                ->groupBy('tahun')
                ->orderBy('tahun')
                ->get();
        $bln1 = '';
        $thn1 = '';
        return view('controlling.backpengeluaran.index', compact('datas','no','bulan','tahun','bln1','thn1'));
    }

    public function filter(Request $request)
    {
        if ($request->bulan == '' && $request->tahun!='') {
            $datas = BackPengeluaran::orderBy('updated_at', 'desc')
                ->whereYear('created_at',$request->tahun)
                ->get();
        }elseif ($request->bulan != '' && $request->tahun=='') {
            $datas = BackPengeluaran::orderBy('updated_at', 'desc')
                ->whereMonth('created_at',$request->bulan)
                ->get();
        }elseif ($request->bulan == '' && $request->tahun=='') {
            $datas = BackPengeluaran::orderBy('updated_at', 'desc')->get();
        }else{
            $datas = BackPengeluaran::orderBy('updated_at', 'desc')
                ->whereMonth('created_at',$request->bulan)
                ->whereYear('created_at',$request->tahun)
                ->get();
        }
        $bln1 = $request->bulan;
        $thn1 = $request->tahun;
        $no=1;
        $bulan = BackPengeluaran::selectRaw('MONTH(created_at) AS bulan')
                ->groupBy('bulan')
                ->orderBy('bulan')
                ->get();
        $tahun = BackPengeluaran::selectRaw('YEAR(created_at) AS tahun')
                ->groupBy('tahun')
                ->orderBy('tahun')
                ->get();
        return view('controlling.backpengeluaran.index', compact('datas','no','bulan','tahun','bln1','thn1'));
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            BackPengeluaran::findOrFail($id)->delete();

            return redirect()
                ->route('backpengeluaran.index')
                ->with('success', 'Data pemasukan berhasil dihapus!');
  
          } catch(\Illuminate\Database\Eloquent\ModelNotFoundException $e){
            return redirect()
                ->route('backpengeluaran.index')
                ->with('error', 'Data pemasukan gagal dihapus!');
          }
    }
}

source/resources/views/controlling/backpengeluaran/index.blade.php
@extends('layouts.app')

@section('title')
SPP | Backup Pengeluaran
@endsection

@section('content')
<!-- Static Table Start -->
<div class="data-table-area mg-b-15">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="sparkline13-list">
                    <div class="sparkline13-hd">
                      <div class="main-sparkline13-hd">
                        <div class="container-sm">
                          <div class="row">
                            <div class="col-md-6">
                              <form action="{{route('backpengeluaran.filter')}}" role="form" method="post">
                                @csrf
                                <div style="float:left; display:flex; flex-direction:row; max-height:55">
                                  <select class="form-control" name="bulan">
                                    <option value="">-- Pilih Bulan -- </option>
                                    <option value="">Semua</option>
                                    @foreach($bulan as $bl)
                                      @php
                                        $bln = ['', 'Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni', 'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember'];
                                        $print = $bln[$bl->bulan];
                                      @endphp
                                      <option  value="{{ $bl->bulan }}">{{ $print }}</option>
                                    @endforeach
                                  </select>
                                  <select style="margin-left:5px;" class="form-control" name="tahun">
                                    <option value="">-- Pilih Tahun  --</option>
                                    <option value="">Semua</option>
                                      @foreach($tahun as $th)
                                      <option  value="{{ $th->tahun }}">{{ $th->tahun }}</option>
                                      @endforeach
                                    </select>
                                    <button type='submit' class="btn btn-info" style="margin-left:5px;">Filter</button>
                                </div>
                              </form>
                            </div>
                            <div class="col-md-6">
                              <div style="float:right;">
                                <form action="{{route('pdf.print')}}" target="_blank" role="form" method="post">
                                  @csrf
                                  <input type="hidden" name='bulan' value='{{$bln1}}'>
                                  <input type="hidden" name='id' value='pengeluaran'>
                                  <input type="hidden" name='tahun' vlaue='{{$thn1}}'>
                                </form>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="sparkline13-graph">
                        <div class="datatable-dashv1-list custom-datatable-overright">
                            <div id="toolbar">
                            </div>
                            <table id="table" data-toggle="table" data-pagination="true" data-search="true" data-show-columns="true" data-show-pagination-switch="true" data-show-refresh="true" data-key-events="true" data-show-toggle="true" data-resizable="true" data-cookie="true"
                                data-cookie-id-table="saveId" data-show-export="true" data-click-to-select="true" data-toolbar="#toolbar">
                                <thead>
                                    <tr>
                                        <th data-field="id">No</th>
                                        <th data-field="tanggal">Tanggal</th>
                                        <th data-field="foto">Foto</th>
                                        <th data-field="title">Title</th>
                                        <th data-field="description">Deskripsi</th>
                                        <th data-field="sumber">Sumber</th>
                                        <th data-field="nominal">Nominal</th>
                                        <th data-field="user">User</th>
                                        <th data-field="Keterangan">Keterangan</th>
                                        <th data-field="action">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                @foreach($datas as $data)
                                  @php
                                    $temp = strtotime($data->created_at);
                                    $tanggal2 = date('d/m/Y', $temp);
                                    $tanggal = date('j - M - Y', $temp);
                                    $url = asset('nota')."/".$data->foto;
                                  @endphp
                                    <tr>
                                        <td>{{$no++}}</td>
                                        <td>{{ $tanggal }}</td>
                                        <td class="avatar text-center">
                                        @if($data->tipe=="img")
                                          <img class="rounded-circle" style="width: 100px; height: 100px;" src="{{ $url }}" alt="">
                                          @elseif($data->tipe=="pdf")
                                          <a href="{{ route('expense.download',$data->foto) }}" title="Download file" style="margin:0;color:blue"><i class="fa fa-download"></i> Download</a>
                                          @endif
                                        </td>
                                        
                                        <td>{{$data->title}}</td>
                                        <td>{{$data->description}}</td>
                                        <td>{{$data->sumber}}</td>
                                        <td>
                                            <div style="text-align: right">
                                                {{number_format($data->nominal,0,',','.')}}
                                            </div>
                                        </td>
                                        <td>{{$data->user}}</td>
                                        <td>{{$data->keterangan}}</td>
                                        <td>
                                          <a href="{{ route('backpengeluaran.destroy',$data) }}" class="btn btn-danger" onclick="event.preventDefault();destroy('{{ route('backpengeluaran.destroy',$data) }}');" title="Hapus"><i class="fa fa-trash"></i> Hapus</a>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
        <!-- Static Table End -->

<!-- hapus -->
<form id="destroy-form" method="POST">
    @method('DELETE')
    @csrf
</form>
@endsection

@push('styles')
<!-- x-editor CSS  -->
    <link rel="stylesheet" href="{{ asset('assets/css/editor/select2.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/editor/datetimepicker.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/editor/bootstrap-editable.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/editor/x-editor-style.css') }}">
    <!-- normalize CSS -->
    <link rel="stylesheet" href="{{ asset('assets/css/data-table/bootstrap-table.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/data-table/bootstrap-editable.css') }}">

     <!-- forms CSS
        ============================================ -->
    <link rel="stylesheet" href="{{asset('assets/css/form/all-type-forms.css')}}">
     <!-- chosen CSS
        ============================================ -->
    <link rel="stylesheet" href="{{asset('assets/css/chosen/bootstrap-chosen.css')}}">

    <!-- datapicker CSS
        ============================================ -->
    <link rel="stylesheet" href="{{asset('assets/css/datapicker/datepicker3.css')}}">
@endpush

@push('scripts')

    <script>
    function editConfirm(tanggal, id,title,description,sumber,nominal)
    {
      $('#title').attr('value',title);
      $('#description').html(description);
      $('#nominal').attr('value',nominal);
      $('#tanggal_edit').attr('value', tanggal);
      $('#sumber_edit').val(sumber);
      $('#sumber_edit_chosen .chosen-single span').html(sumber);
      
      $('#editPengeluaran').attr('action',"{{ url('expense') }}/"+id)
      $('#modalUpdate').modal();
    }

    function destroy(action){
        swal({
            title: 'Apakah anda yakin?',
            text: 'Setelah dihapus, Anda tidak akan dapat mengembalikan data ini!',
            icon: 'warning',
            buttons: ["Cancel", "Yes!"],
        }).then(function(value) {
            if (value) {
            document.getElementById('destroy-form').setAttribute('action', action);
            document.getElementById('destroy-form').submit();
            }else {
            swal("Data kamu aman!");
        }
        });
    }
    </script>
    
@endpush

@push('scripts-asset')
<!-- data table JS
        ============================================ -->
    <script src="{{ asset('assets/js/data-table/bootstrap-table.js') }}"></script>
    <script src="{{ asset('assets/js/data-table/tableExport.js') }}"></script>
    <script src="{{ asset('assets/js/data-table/data-table-active.js') }}"></script>
    <script src="{{ asset('assets/js/data-table/bootstrap-table-editable.js') }}"></script>
    <script src="{{ asset('assets/js/data-table/bootstrap-editable.js') }}"></script>
    <script src="{{ asset('assets/js/data-table/bootstrap-table-resizable.js') }}"></script>
    <script src="{{ asset('assets/js/data-table/colResizable-1.5.source.js') }}"></script>
    <script src="{{ asset('assets/js/data-table/bootstrap-table-export.js') }}"></script>
    <!--  editable JS
        ============================================ -->
    <script src="{{ asset('assets/js/editable/jquery.mockjax.js') }}"></script>
    <script src="{{ asset('assets/js/editable/mock-active.js') }}"></script>
    <script src="{{ asset('assets/js/editable/select2.js') }}"></script>
    <script src="{{ asset('assets/js/editable/moment.min.js') }}"></script>
    <script src="{{ asset('assets/js/editable/bootstrap-datetimepicker.js') }}"></script>
    <script src="{{ asset('assets/js/editable/bootstrap-editable.js') }}"></script>
    <script src="{{ asset('assets/js/editable/xediable-active.js') }}"></script>

    <!-- icheck JS
        ============================================ -->
    <script src="{{ asset('assets/js/icheck/icheck.min.js')}}"></script>
    <script src="{{ asset('assets/js/icheck/icheck-active.js')}}"></script>

    <!-- chosen JS
        ============================================ -->
    <script src="{{ asset('assets/js/chosen/chosen.jquery.js')}}"></script>
    <script src="{{ asset('assets/js/chosen/chosen-active.js')}}"></script>

    <!-- input-mask JS
        ============================================ -->
    <script src="{{ asset('assets/js/input-mask/jasny-bootstrap.min.js')}}"></script>

    <!-- datapicker JS
        ============================================ -->
    <script src="{{ asset('assets/js/datapicker/bootstrap-datepicker.js')}}"></script>
    <script src="{{ asset('assets/js/datapicker/datepicker-active.js')}}"></script>
  @endpush

@push('breadcrumb-left')
<h3>Data Backup Pengeluaran</h3>
@endpush

@push('breadcrumb-right')
<div style="float:right">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb" style="margin-bottom:0">
            <li class="breadcrumb-item"><a href="{{ url('/')}}">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Pengeluaran</li>
        </ol>
    </nav>
</div>
@endpush