source/routes/web.php
<?php
use App\Http\Controllers\MenuRekapController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/**
 * @description Route home
 *  
 */
Route::get('/', function () {
    return redirect()->route('home');
});

 Route::get('home', 'HomeController@index')->name('home');

//============================MASTER=================

//majors
Route::resource('/majors', 'MajorController')->middleware('cekstatus');
//angkatan
Route::resource('/angkatan', 'AngkatanController')->middleware('cekstatus');
//student
Route::get('students/naik_kelas', 'StudentController@naikKelas')->name('students.naikkelas')->middleware('cekstatus');
Route::get('students/turun_kelas', 'StudentController@turunKelas')->name('students.turunkelas')->middleware('cekstatus');
Route::post('students_filter', 'StudentController@filter')->name('students.filter')->middleware('cekstatus');
Route::resource('students', 'StudentController')->middleware('cekstatus');

/**
 * Route resource untuk User
 */
Route::resource('user', 'UserController');

/**
 * Route resource untuk User
 */
Route::resource('history', 'HistoryController');

/**
 * Route resource untuk Kategori Pembiayaan
 */
Route::resource('financing', 'FinancingCategoryController')->middleware('cekstatus');
Route::get('financing/history/{id}', 'FinancingCategoryController@history')->middleware('cekstatus');
Route::get('financing/ajax/periode/{id}', 'FinancingCategoryController@periode_ajax')->middleware('cekstatus');
Route::get('financing/ajax/form/{id}', 'FinancingCategoryController@showForm')->middleware('cekstatus');
Route::get('periode/{id}','PeriodeController@periode')->middleware('cekstatus');
Route::get('periode/ajax/{id}','PeriodeController@ajax')->middleware('cekstatus');
Route::get('periode/all/{category}','PeriodeController@all')->name('periode.all')->middleware('cekstatus');
Route::get('periode/all/{category}/{jurusan}','PeriodeController@showAll')->name('periode.all.setting')->middleware('cekstatus');
Route::put('periode/all/{category}/{jurusan}','PeriodeController@showAllUpdate')->name('periode.all.setting.update')->middleware('cekstatus');
Route::get('periode/jurusan/{category}','PeriodeController@showJurusan')->name('periode.jurusan.setting')->middleware('cekstatus');
Route::put('periode/jurusan/{category}','PeriodeController@showJurusanUpdate')->name('periode.jurusan.setting.update')->middleware('cekstatus');
Route::get('periode/angkatan/{category}','PeriodeController@showAngkatan')->name('periode.angkatan.setting')->middleware('cekstatus');
Route::put('periode/angkatan/{category}','PeriodeController@showAngkatanUpdate')->name('periode.angkatan.setting.update')->middleware('cekstatus');

/**
 * Route Periode Pembayaran
 */
Route::get('financing/periode/{id}', 'FinancingCategoryController@periode')->name('financing.periode')->middleware('cekstatus');
Route::put('financing/periode/{id}', 'FinancingCategoryController@periode_update')->name('periode.update')->middleware('cekstatus');
Route::post('financing/periode/store', 'FinancingCategoryController@periode_store')->name('periode.store')->middleware('cekstatus');
Route::delete('financing/periode/destroy/{id}/{kategori}', 'FinancingCategoryController@periode_destroy')->name('periode.destroy')->middleware('cekstatus');
 
/**
 * Route resource untuk Pembayaran
 */
Route::resource('payment', 'PaymentController')->middleware('cekstatus');
Route::post('payment/filter', 'PaymentController@showFilter')->name('payment.filter')->middleware('cekstatus');
Route::get('payment/category/{id}', 'PaymentController@indexKategori2')->name('payment.category')->middleware('cekstatus');
Route::get('payment/ajax/{id}', 'PaymentController@ajaxIndex')->name('payment.category.ajax')->middleware('cekstatus');
Route::get('payment/ajax_perbulan/{id}', 'PaymentController@ajaxIndexPerbulan')->name('payment.category.ajax.perbulan')->middleware('cekstatus');
/**
 * Route pembayaran jenis "sekali bayar"
 */
Route::post('payment/metode','PaymentController@storeMetodePembayaran')->name('payment.storeMethod')->middleware('cekstatus');
Route::get('payment/details/{id_category}/{id_siswa}/{id_payment}','PaymentController@details')->name('payment.details.cicilan')->middleware('cekstatus');
Route::post('payment/details/store','PaymentController@cicilanStore')->name('payment.details.cicilan.store')->middleware('cekstatus');
/**
 * Route pembayaran jenis "per bulan"
 */
Route::get('payment/perbulan/{id}', 'PaymentController@showBulanan')->name('payment.monthly.show')->middleware('cekstatus');
Route::get('payment/perbulan/detail/{payment}/{student}/{category}', 'PaymentController@showBulananDetail')->name('payment.monthly.show.detail')->middleware('cekstatus');
Route::get('payment/perbulan/detail/ajax/{periode}', 'PaymentController@ajaxBulananDetail')->name('payment.monthly.ajax.detail')->middleware('cekstatus');
Route::post('payment/perbulan/detail/','PaymentController@bulananStore')->name('payment.monthly.detail.store')->middleware('cekstatus');
Route::put('payment/perbulan/detail/update','PaymentController@updateStatusBulanan')->name('payment.monthly.detail.update')->middleware('cekstatus');
Route::post('payment/perbulan/detail/add','PaymentController@addPeriodeBulanan')->name('payment.monthly.detail.add')->middleware('cekstatus');
Route::get('payment/perbulan/detail/delete/{id}','PaymentController@deletePeriodeBulanan')->name('payment.monthly.detail.delete')->middleware('cekstatus');
Route::get('payment/detail/delete/{id}','PaymentController@deletePeriode')->name('payment.detail.delete')->middleware('cekstatus');
Route::get('payment/cicilan/delete/{id}/{payment}','PaymentController@deleteCicilan')->name('payment.cicilan.delete')->middleware('cekstatus');
/**
 * Route resource untuk Pengeluaran 
 */
Route::resource('expense', 'ExpenseController')->middleware('cekstatus');
Route::post('expense/filter', 'ExpenseController@filter')->name('expense.filter')->middleware('cekstatus');
Route::get('expense/download/{path}', 'ExpenseController@download')->name('expense.download')->middleware('cekstatus');

/**
 * Route resource untuk Pembayaran
 */ 
Route::resource('rekap', 'RekapController');
Route::get('rekap/ajax/custom_tunggakan', 'MenuRekapController@nominalRekapTunggakanArray');
Route::get('rekap/ajax/total_tunggakan', function ()
{
    $tunggakan = MenuRekapController::nominalRekapTunggakan();
    return number_format($tunggakan,0,',','.');
});

/**
 * Route resource untuk Pembayaran
 */
Route::resource('income', 'IncomeController')->middleware('cekstatus');
Route::post('income/filter', 'IncomeController@filter')->name('income.filter')->middleware('cekstatus');
Route::get('income/download/{path}', 'IncomeController@download')->name('income.download')->middleware('cekstatus');


/**
 * Route Login
 */
 Auth::routes();
Route::get('/change', 'HomeController@edit')->name('password.edit');
Route::post('/change', 'HomeController@update')->name('password.ubah');

/**
 * Route Print
 */
Route::get('export','RekapController@index')->name('pdf');
Route::post('export','RekapController@print')->name('pdf.print');
Route::get('export_kwitansi','RekapController@listdata')->name('pdf.print.kwitansi');
Route::get('export/bulanan/{nama}/{id}','RekapController@rekapBulanan')->name('pdf.print.rekap.bulanan');
Route::post('export/siswa/','RekapController@rekapSiswa')->name('pdf.print.rekap.siswa');
//untuk jenis pembayaran bayar per bulan
Route::get('export/bulanan/rekap/{nama}/{id}/{filter?}','RekapController@rekapBulanan')->name('pdf.print.rekap.bulanan');
Route::get('export/bulanan/onepage/{nama}/{payment}/{kategori}','RekapController@kwitansiBulanan')->name('pdf.print.bulanan');
Route::get('export/bulanan/detail/{nama}/{payment}','RekapController@kwitansiBulananSatuan')->name('pdf.print.bulanan.detail');
//untuk jenis pembayaran sekali bayar
Route::post('export/sesekali/rekap/','RekapController@rekapSesekali')->name('pdf.print.rekap.sesekali');
Route::get('export/sesekali/onepage/{siswa}/{payment}/{kategory}','RekapController@kwitansiSesekali')->name('pdf.print.sesekali');
Route::get('export/sesekali/detail/{nama}/{payment}/{stat?}','RekapController@kwitansiSesekaliSatuan')->name('pdf.print.sesekali.detail');
//ajax
Route::get('export/ajax/major/{category}/{kelas?}','RekapController@ajaxMajor')->name('rekap.ajax.major');
Route::get('export/ajax/kelas/{category}/{major?}','RekapController@ajaxKelas')->name('rekap.ajax.kelas');

Route::get('laporan_bos','RekapController@ulala');
/**
 * Route Simpanan
 */
 Route::get('simpanan', 'SimpananController@index')->name('simpanan')->middleware('cekstatus');
 Route::post('simpanan/filter', 'SimpananController@filter')->name('simpanan.filter')->middleware('cekstatus');

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/rekap_Pemasukan', 'MenuRekapController@indexPemasukan')->name('rekap.pemasukan');
Route::get('/rekap_Pengeluaran', 'MenuRekapController@indexPengeluaran')->name('rekap.pengeluaran');
Route::get('/rekap_bukbes', 'MenuRekapController@indexBB')->name('rekap.bukbes');
Route::get('/rekap_tunggakan/{stat?}', 'MenuRekapController@indexTunggakan')->name('rekap.tunggakan');

Route::post('/rekap_Pemasukan', 'MenuRekapController@indexPemasukanFilter')->name('rekap.pemasukan.filter');
Route::post('/rekap_Pengeluaran', 'MenuRekapController@indexPengeluaranFilter')->name('rekap.pengeluaran.filter');
Route::post('/rekap_bukbes', 'MenuRekapController@indexBukuBesarFilter')->name('rekap.bukbes.filter');
Route::post('/rekap_tunggakan/{stat?}', 'MenuRekapController@indexTunggakanFilter')->name('rekap.tunggakan.filter');

source/app/Major.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Major extends Model
{
    /**
     * Nama table yang digunakan
     */
    protected $table = 'majors';

    /**
     * Kolom yang dapat di isi
     */
    protected $fillable = [
        "nama",
        "inisial",
    ];
    
    /**
     * Relasi One to Many
     */
    public function students()
    {
        return $this->hasMany('App\Student');
    }
 
    /**
     * Relasi One to Many
     */
    public function periode()
    {
        return $this->hasMany('App\PaymentPeriode');
    }

    public function category()
    {
        return $this->hasMany('App\FinancingCategory');
    }
}

source/app/Http/Controllers/MajorController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

use App\Major;
use App\PaymentPeriode;
use App\FinancingCategory;
use DB;

class MajorController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $majors = Major::orderBy('updated_at','desc')->get();
        $no=1;
        return view('master.major.index', compact('majors','no'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'jurusan' => 'required',
            'alias' => 'required',
        ]);

        try {
            $req = $request->all();
            Major::create([
                'id' => null,
                'nama' => $req['jurusan'],
                'inisial' => $req['alias'],
            ]);
            $id = DB::getPdo()->lastInsertId();
            $categories = FinancingCategory::join('financing_periodes','financing_periodes.financing_category_id','=','financing_categories.id')
                            ->join('angkatans','angkatans.id','=','financing_periodes.angkatan_id')
                            ->groupBy(['financing_categories.id','financing_periodes.angkatan_id'])
                            ->selectRaw('financing_categories.*, financing_periodes.id as periode_id, financing_periodes.major_id, financing_periodes.angkatan_id, 
                            financing_periodes.nominal, angkatans.status')
                            ->get();
            foreach ($categories as $category) {
                $count_jurusan = $category->periode->groupBy('major_id')->count();
                if($count_jurusan>1){
                    PaymentPeriode::create([
                        'id' => null,
                        'financing_category_id' => $category->id,
                        'angkatan_id' => $category->angkatan_id,
                        'major_id' => $id
                    ]);
                }
            }
            return redirect()
              ->route('majors.index')
              ->with('success', 'Data jurusan berhasil disimpan!');

        }catch(Exception $e){
          return redirect()
              ->route('majors.create')
              ->with('error', 'Data jurusan gagal disimpan!');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'jurusan' => 'required',
        ]);

        try {
            $req = $request->all();
            $major = Major::findOrFail($id);
            $major->nama = $req['jurusan'];
            $major->inisial = $req['alias'];
            $major->save();

            return redirect()
                ->route('majors.index')
                ->with('success', 'Data jurusan berhasil diubah!');

        } catch(\Illuminate\Database\Eloquent\ModelNotFoundException $e){
          return redirect()
              ->route('majors.index')
              ->with('error', 'Data jurusan gagal diubah!');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $major = Major::findOrFail($id);
            $ids = PaymentPeriode::select('financing_category_id')->groupBy('financing_category_id')->where('major_id', $id)->get();
            foreach ($ids as $key) {
                FinancingCategory::find($key->financing_category_id)->delete();
            }
            $major->delete();
            return redirect()
                ->route('majors.index')
                ->with('success', 'Data jurusan berhasil dihapus!');
  
          } catch(\Illuminate\Database\Eloquent\ModelNotFoundException $e){
            return redirect()
                ->route('majors.index')
                ->with('error', 'Data jurusan gagal dihapus!');
          }
    }
}

source/resources/views/master/major/index.blade.php
@extends('layouts.app')

@section('title')
SPP | Jurusan
@endsection

@section('content')
<div id="edit-form">
<div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
    <div class="hpanel hblue sparkline16-list responsive-mg-b-30">
        <div class="panel-body custom-panel-jw">
            <h3>Form Ubah Jurusan</h3>
            <hr>
            <div class="sparkline16-graph">
                <div class="date-picker-inner">
                    <div class="basic-login-inner">
                        <form method="post" id="form-jurusan">
                            @method('PUT')
                            @csrf

                            <div class="form-group">
                                <label>Nama Jurusan</label>
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-mortar-board"></i></span>
                                    <input type="text" class="form-control" name="jurusan"
                                        placeholder="Masukan Nama Jurusan">
                                </div>
                            </div>
                            <div class="form-group">
                                <label>Nama Alias</label>
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-anchor"></i></span>
                                    <input type="text" class="form-control" name="alias"
                                        placeholder="Masukan Nama Alias">
                                </div>
                            </div>
                            <div class="login-btn-inner">
                                <div class="inline-remember-me">
                                    <input type="submit" value="Submit"
                                        class="btn btn-sm btn-primary pull-right login-submit-cs">
                                    <label>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

<div id="add-form">
<div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
    <div class="hpanel hblue sparkline16-list responsive-mg-b-30">
        <div class="panel-body custom-panel-jw">
            <h3>Form Tambah Jurusan</h3>
            <hr>
            <div class="sparkline16-graph">
                <div class="date-picker-inner">
                    <div class="basic-login-inner">
                        <form action="{{route('majors.store')}}" method="post" id="form-jurusan-add">
                            @csrf

                            <div class="form-group">
                                <label>Nama Jurusan</label>
                                <div class="input-group date">
                                    <span class="input-group-addon"><i class="fa fa-mortar-board"></i></span>
                                    <input type="text" class="form-control" name="jurusan" id="a"
                                        placeholder="Masukan Nama Jurusan">
                                </div>
                            </div>
                            
                            <div class="form-group">
                                <label>Nama Alias</label>
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-anchor"></i></span>
                                    <input type="text" class="form-control" name="alias"
                                        placeholder="Masukan Nama Alias">
                                </div>
                            </div>
                            <div class="login-btn-inner">
                                <div class="inline-remember-me">
                                    <input type="submit" value="Submit"
                                        class="btn btn-sm btn-primary pull-right login-submit-cs">
                                    <label>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
<div class="col-lg-8 col-md-6 col-sm-6 col-xs-12">
    <div class="hpanel hblue contact-panel contact-panel-cs responsive-mg-b-30">
        <div class="panel-body custom-panel-jw">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="sparkline13-list">
                            <div class="sparkline13-hd">
                                <div class="container-sm">
                                    <div class="main-sparkline13-hd">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <h3>Data Jurusan</h3>
                                            </div>
                                            <div class="col-md-6" >
                                            <div style="float:right">
                                            <button class="btn btn-success" onclick="addConfirm()">
                                                <i class="fa fa-plus" ></i> Tambah
                                            </button>
                                            </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="sparkline13-graph">
                                <div class="datatable-dashv1-list custom-datatable-overright">
                                    <div id="toolbar">
                                    </div>
                                    <table id="table" data-toggle="table" data-pagination="true" data-search="true"
                                        data-show-columns="true" data-show-pagination-switch="true"
                                        data-show-refresh="true" data-key-events="true" data-show-toggle="true"
                                        data-resizable="true" data-cookie="true" data-cookie-id-table="saveId"
                                        data-show-export="true" data-click-to-select="true" data-toolbar="#toolbar">
                                        <thead>
                                            <tr>
                                                <th data-field="id">No</th>
                                                <th data-field="jurusan" data-editable="false">Nama Jurusan</th>
                                                <th data-field="alias" data-editable="false">Nama Alias</th>
                                                <th data-field="action" data-editable="false">
                                                    <div style="text-align:center;">Action</div>
                                                </th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach($majors as $data)
                                            <tr>
                                                <td>{{$no++}}</td>
                                                <td>{{$data->nama}}</td>
                                                <td>{{$data->inisial}}</td>
                                                <td>
                                                    <div style="text-align:center;">
                                                        <a href="#" class="btn btn-warning"
                                                            onclick="editConfirm({{$data}})"
                                                            title="Edit" style="margin-top:0;"><i
                                                                class="fa fa-edit"></i></a>
                                                        <!-- <a href="{{ route('majors.destroy',$data) }}"
                                                            class="btn btn-danger"
                                                            onclick="event.preventDefault();destroy('{{ route('majors.destroy',$data) }}');"
                                                            title="Hapus" style="margin-top:0;"><i
                                                                class="fa fa-trash"></i></a> -->
                                                    </div>
                                                </td>
                                            </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Static Table End -->

<!-- hapus -->
<form id="destroy-form" method="POST">
    @method('DELETE')
    @csrf
</form>
@endsection

@push('styles')
<!-- x-editor CSS  -->
<link rel="stylesheet" href="{{ asset('assets/css/editor/select2.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/editor/datetimepicker.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/editor/bootstrap-editable.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/editor/x-editor-style.css') }}">
<!-- normalize CSS -->
<link rel="stylesheet" href="{{ asset('assets/css/data-table/bootstrap-table.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/data-table/bootstrap-editable.css') }}">
@endpush

@push('scripts')

<script>
    $(document).ready(function(){
        $('#add-form').show();
        $('#edit-form').hide();
    });
    

    function editConfirm(data) {
        $('#add-form').hide();
        $('#edit-form').show();
        $('input[name=id]').attr('value', data.id);
        $('input[name=jurusan]').attr('value', data.nama);
        $('input[name=alias]').attr('value', data.inisial);
        $('#form-jurusan').attr('action', "{{ url('majors') }}/" + data.id);
        $('input[name=jurusan]').focus();
    }

    function addConfirm() {
        $('#add-form').show();
        $('#a').attr('value','');
        $('#a').focus();
        $('#edit-form').hide();
    }

    function destroy(action) {
        swal({
            title: 'Apakah anda yakin?',
            text: 'Setelah dihapus, Anda tidak akan dapat mengembalikan data ini!',
            icon: 'warning',
            buttons: ["Cancel", "Yes!"],
        }).then(function (value) {
            if (value) {
                document.getElementById('destroy-form').setAttribute('action', action);
                document.getElementById('destroy-form').submit();
            } else {
                swal("Data kamu aman!");
            }
        });
    }

</script>
<!-- data table JS
		============================================ -->
<script src="{{ asset('assets/js/data-table/bootstrap-table.js') }}"></script>
<script src="{{ asset('assets/js/data-table/tableExport.js') }}"></script>
<script src="{{ asset('assets/js/data-table/data-table-active.js') }}"></script>
<script src="{{ asset('assets/js/data-table/bootstrap-table-editable.js') }}"></script>
<script src="{{ asset('assets/js/data-table/bootstrap-editable.js') }}"></script>
<script src="{{ asset('assets/js/data-table/bootstrap-table-resizable.js') }}"></script>
<script src="{{ asset('assets/js/data-table/colResizable-1.5.source.js') }}"></script>
<script src="{{ asset('assets/js/data-table/bootstrap-table-export.js') }}"></script>
<!--  editable JS
		============================================ -->
<script src="{{ asset('assets/js/editable/jquery.mockjax.js') }}"></script>
<script src="{{ asset('assets/js/editable/mock-active.js') }}"></script>
<script src="{{ asset('assets/js/editable/select2.js') }}"></script>
<script src="{{ asset('assets/js/editable/moment.min.js') }}"></script>
<script src="{{ asset('assets/js/editable/bootstrap-datetimepicker.js') }}"></script>
<script src="{{ asset('assets/js/editable/bootstrap-editable.js') }}"></script>
<script src="{{ asset('assets/js/editable/xediable-active.js') }}"></script>
@endpush

@push('breadcrumb-left')
<h2>Menu Jurusan</h2>
@endpush
@push('breadcrumb-right')
<div style="float:right">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb" style="margin-bottom:0">
            <li class="breadcrumb-item"><a href="{{ url('/')}}">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Jurusan</li>
        </ol>
    </nav>
</div>
@endpush