source/routes/web.php
<?php
use App\Http\Controllers\MenuRekapController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/**
 * @description Route home
 *  
 */
Route::get('/', function () {
    return redirect()->route('home');
});

 Route::get('home', 'HomeController@index')->name('home');

//============================MASTER=================

//majors
Route::resource('/majors', 'MajorController')->middleware('cekstatus');
//angkatan
Route::resource('/angkatan', 'AngkatanController')->middleware('cekstatus');
//student
Route::get('students/naik_kelas', 'StudentController@naikKelas')->name('students.naikkelas')->middleware('cekstatus');
Route::get('students/turun_kelas', 'StudentController@turunKelas')->name('students.turunkelas')->middleware('cekstatus');
Route::post('students_filter', 'StudentController@filter')->name('students.filter')->middleware('cekstatus');
Route::resource('students', 'StudentController')->middleware('cekstatus');

/**
 * Route resource untuk User
 */
Route::resource('user', 'UserController');

/**
 * Route resource untuk User
 */
Route::resource('history', 'HistoryController');

/**
 * Route resource untuk Kategori Pembiayaan
 */
Route::resource('financing', 'FinancingCategoryController')->middleware('cekstatus');
Route::get('financing/history/{id}', 'FinancingCategoryController@history')->middleware('cekstatus');
Route::get('financing/ajax/periode/{id}', 'FinancingCategoryController@periode_ajax')->middleware('cekstatus');
Route::get('financing/ajax/form/{id}', 'FinancingCategoryController@showForm')->middleware('cekstatus');
Route::get('periode/{id}','PeriodeController@periode')->middleware('cekstatus');
Route::get('periode/ajax/{id}','PeriodeController@ajax')->middleware('cekstatus');
Route::get('periode/all/{category}','PeriodeController@all')->name('periode.all')->middleware('cekstatus');
Route::get('periode/all/{category}/{jurusan}','PeriodeController@showAll')->name('periode.all.setting')->middleware('cekstatus');
Route::put('periode/all/{category}/{jurusan}','PeriodeController@showAllUpdate')->name('periode.all.setting.update')->middleware('cekstatus');
Route::get('periode/jurusan/{category}','PeriodeController@showJurusan')->name('periode.jurusan.setting')->middleware('cekstatus');
Route::put('periode/jurusan/{category}','PeriodeController@showJurusanUpdate')->name('periode.jurusan.setting.update')->middleware('cekstatus');
Route::get('periode/angkatan/{category}','PeriodeController@showAngkatan')->name('periode.angkatan.setting')->middleware('cekstatus');
Route::put('periode/angkatan/{category}','PeriodeController@showAngkatanUpdate')->name('periode.angkatan.setting.update')->middleware('cekstatus');

/**
 * Route Periode Pembayaran
 */
Route::get('financing/periode/{id}', 'FinancingCategoryController@periode')->name('financing.periode')->middleware('cekstatus');
Route::put('financing/periode/{id}', 'FinancingCategoryController@periode_update')->name('periode.update')->middleware('cekstatus');
Route::post('financing/periode/store', 'FinancingCategoryController@periode_store')->name('periode.store')->middleware('cekstatus');
Route::delete('financing/periode/destroy/{id}/{kategori}', 'FinancingCategoryController@periode_destroy')->name('periode.destroy')->middleware('cekstatus');
 
/**
 * Route resource untuk Pembayaran
 */
Route::resource('payment', 'PaymentController')->middleware('cekstatus');
Route::post('payment/filter', 'PaymentController@showFilter')->name('payment.filter')->middleware('cekstatus');
Route::get('payment/category/{id}', 'PaymentController@indexKategori2')->name('payment.category')->middleware('cekstatus');
Route::get('payment/ajax/{id}', 'PaymentController@ajaxIndex')->name('payment.category.ajax')->middleware('cekstatus');
Route::get('payment/ajax_perbulan/{id}', 'PaymentController@ajaxIndexPerbulan')->name('payment.category.ajax.perbulan')->middleware('cekstatus');
/**
 * Route pembayaran jenis "sekali bayar"
 */
Route::post('payment/metode','PaymentController@storeMetodePembayaran')->name('payment.storeMethod')->middleware('cekstatus');
Route::get('payment/details/{id_category}/{id_siswa}/{id_payment}','PaymentController@details')->name('payment.details.cicilan')->middleware('cekstatus');
Route::post('payment/details/store','PaymentController@cicilanStore')->name('payment.details.cicilan.store')->middleware('cekstatus');
/**
 * Route pembayaran jenis "per bulan"
 */
Route::get('payment/perbulan/{id}', 'PaymentController@showBulanan')->name('payment.monthly.show')->middleware('cekstatus');
Route::get('payment/perbulan/detail/{payment}/{student}/{category}', 'PaymentController@showBulananDetail')->name('payment.monthly.show.detail')->middleware('cekstatus');
Route::get('payment/perbulan/detail/ajax/{periode}', 'PaymentController@ajaxBulananDetail')->name('payment.monthly.ajax.detail')->middleware('cekstatus');
Route::post('payment/perbulan/detail/','PaymentController@bulananStore')->name('payment.monthly.detail.store')->middleware('cekstatus');
Route::put('payment/perbulan/detail/update','PaymentController@updateStatusBulanan')->name('payment.monthly.detail.update')->middleware('cekstatus');
Route::post('payment/perbulan/detail/add','PaymentController@addPeriodeBulanan')->name('payment.monthly.detail.add')->middleware('cekstatus');
Route::get('payment/perbulan/detail/delete/{id}','PaymentController@deletePeriodeBulanan')->name('payment.monthly.detail.delete')->middleware('cekstatus');
Route::get('payment/detail/delete/{id}','PaymentController@deletePeriode')->name('payment.detail.delete')->middleware('cekstatus');
Route::get('payment/cicilan/delete/{id}/{payment}','PaymentController@deleteCicilan')->name('payment.cicilan.delete')->middleware('cekstatus');
/**
 * Route resource untuk Pengeluaran 
 */
Route::resource('expense', 'ExpenseController')->middleware('cekstatus');
Route::post('expense/filter', 'ExpenseController@filter')->name('expense.filter')->middleware('cekstatus');
Route::get('expense/download/{path}', 'ExpenseController@download')->name('expense.download')->middleware('cekstatus');

/**
 * Route resource untuk Pembayaran
 */ 
Route::resource('rekap', 'RekapController');
Route::get('rekap/ajax/custom_tunggakan', 'MenuRekapController@nominalRekapTunggakanArray');
Route::get('rekap/ajax/total_tunggakan', function ()
{
    $tunggakan = MenuRekapController::nominalRekapTunggakan();
    return number_format($tunggakan,0,',','.');
});

/**
 * Route resource untuk Pembayaran
 */
Route::resource('income', 'IncomeController')->middleware('cekstatus');
Route::post('income/filter', 'IncomeController@filter')->name('income.filter')->middleware('cekstatus');
Route::get('income/download/{path}', 'IncomeController@download')->name('income.download')->middleware('cekstatus');


/**
 * Route Login
 */
 Auth::routes();
Route::get('/change', 'HomeController@edit')->name('password.edit');
Route::post('/change', 'HomeController@update')->name('password.ubah');

/**
 * Route Print
 */
Route::get('export','RekapController@index')->name('pdf');
Route::post('export','RekapController@print')->name('pdf.print');
Route::get('export_kwitansi','RekapController@listdata')->name('pdf.print.kwitansi');
Route::get('export/bulanan/{nama}/{id}','RekapController@rekapBulanan')->name('pdf.print.rekap.bulanan');
Route::post('export/siswa/','RekapController@rekapSiswa')->name('pdf.print.rekap.siswa');
//untuk jenis pembayaran bayar per bulan
Route::get('export/bulanan/rekap/{nama}/{id}/{filter?}','RekapController@rekapBulanan')->name('pdf.print.rekap.bulanan');
Route::get('export/bulanan/onepage/{nama}/{payment}/{kategori}','RekapController@kwitansiBulanan')->name('pdf.print.bulanan');
Route::get('export/bulanan/detail/{nama}/{payment}','RekapController@kwitansiBulananSatuan')->name('pdf.print.bulanan.detail');
//untuk jenis pembayaran sekali bayar
Route::post('export/sesekali/rekap/','RekapController@rekapSesekali')->name('pdf.print.rekap.sesekali');
Route::get('export/sesekali/onepage/{siswa}/{payment}/{kategory}','RekapController@kwitansiSesekali')->name('pdf.print.sesekali');
Route::get('export/sesekali/detail/{nama}/{payment}/{stat?}','RekapController@kwitansiSesekaliSatuan')->name('pdf.print.sesekali.detail');
//ajax
Route::get('export/ajax/major/{category}/{kelas?}','RekapController@ajaxMajor')->name('rekap.ajax.major');
Route::get('export/ajax/kelas/{category}/{major?}','RekapController@ajaxKelas')->name('rekap.ajax.kelas');

Route::get('laporan_bos','RekapController@ulala');
/**
 * Route Simpanan
 */
 Route::get('simpanan', 'SimpananController@index')->name('simpanan')->middleware('cekstatus');
 Route::post('simpanan/filter', 'SimpananController@filter')->name('simpanan.filter')->middleware('cekstatus');

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/rekap_Pemasukan', 'MenuRekapController@indexPemasukan')->name('rekap.pemasukan');
Route::get('/rekap_Pengeluaran', 'MenuRekapController@indexPengeluaran')->name('rekap.pengeluaran');
Route::get('/rekap_bukbes', 'MenuRekapController@indexBB')->name('rekap.bukbes');
Route::get('/rekap_tunggakan/{stat?}', 'MenuRekapController@indexTunggakan')->name('rekap.tunggakan');

Route::post('/rekap_Pemasukan', 'MenuRekapController@indexPemasukanFilter')->name('rekap.pemasukan.filter');
Route::post('/rekap_Pengeluaran', 'MenuRekapController@indexPengeluaranFilter')->name('rekap.pengeluaran.filter');
Route::post('/rekap_bukbes', 'MenuRekapController@indexBukuBesarFilter')->name('rekap.bukbes.filter');
Route::post('/rekap_tunggakan/{stat?}', 'MenuRekapController@indexTunggakanFilter')->name('rekap.tunggakan.filter');

source/resources/views/layouts/app_login.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
        
    </div>
    
</body>
</html>

source/resources/views/layouts/message.blade.php
@if(Session::has('error'))
    <input type="hidden" id="status" value="{{Session::get('error')}}">
    <script type='text/javascript'>
      window.onload = function(event) {
        let sts = document.getElementById('status').value;
        swal('Error!', sts, 'error')
      };
  </script> 
@endif

@if(Session::has('success'))
  <input type="hidden" id="status" value="{{Session::get('success')}}">
    <script type='text/javascript'>
      window.onload = function(event) {
        let sts = document.getElementById('status').value;
        swal('Succes!', sts, 'success')
      };
  </script> 
@endif

source/resources/views/layouts/navbar-mobile.blade.php
<div class="mobile-menu">
    <nav id="dropdown">
        <ul class="mobile-menu-nav">
            <li>
                <a title="Dashboard" class="icon-wrap" href="{{ url('/') }}" aria-expanded="false">
                    <span class="fa fa-home sub-icon-mg" aria-hidden="true"></span>
                    <span class="mini-click-non ">Dashboard</span>
                </a>
            </li>
            <li>
                <a class="has-arrow" title="Data Master" href="#" aria-expanded="false">
                    <span class="fa fa-diamond sub-icon-mg" aria-hidden="true"></span>
                    <span class="mini-click-non ">Master</span>
                </a>
                <ul class="submenu-angle" aria-expanded="false">
                    <li><a title="Data Master Siswa" href="{{ route('students.index') }}"><span class="mini-sub-pro">Siswa</span></a></li>
                    <li><a title="Data Master Jurusan" href="{{ route('majors.index') }}"><span class="mini-sub-pro">Jurusan</span></a></li>
                    <li><a title="Data Master Angkatan" href="{{ route('angkatan.index') }}"><span class="mini-sub-pro">Angkatan</span></a></li>
                    <li><a title="Data Master Kategori Pembiayaan" href="{{ url('financing') }}"><span class="mini-sub-pro">Kategori
                                Pembiayaan</span></a></li>
                </ul>
            </li>
            <li>
                <a title="Data Pembayaran" class="" href="{{ route('payment.index') }}" aria-expanded="false">
                    <span class="fa fa-credit-card sub-icon-mg" aria-hidden="true"></span>
                    <span class="mini-click-non ">Pembayaran</span>
                </a>
            </li>
            <li>
                <a title="Data Pembayaran" class="" href="{{ route('history.index') }}" aria-expanded="false">
                    <span class="educate-icon educate-library icon-wrap" aria-hidden="true"></span>
                    <span class="mini-click-non ">Histori</span>
                </a>
            </li>
            <li>
                <a title="Data Pemasukan" class="" href="{{ route('income.index') }}" aria-expanded="false">
                    <span class="educate-icon educate-department sub-icon-mg" aria-hidden="true"></span>
                    <span class="mini-click-non ">Pemasukan</span>
                </a>
            </li>
            <li>
                <a title="Data Pengeluaran" class="" href="{{ route('expense.index') }}" aria-expanded="false">
                    <span class="fa fa-tags sub-icon-mg" aria-hidden="true"></span>
                    <span class="mini-click-non ">Pengeluaran</span>
                </a>
            </li>
            <li>
                <a title="Simpanan" class="" href="{{ url('simpanan') }}" aria-expanded="false">
                    <span class="fa fa-id-badge sub-icon-mg" aria-hidden="true"></span>
                    <span class="mini-click-non ">Simpanan</span>
                </a>
            </li>
            <li>
                <a title="Rekapitulasi" class="" href="{{ route('rekap.index') }}" aria-expanded="false">
                    <span class="fa fa-files-o sub-icon-mg" aria-hidden="true"></span>
                    <span class="mini-click-non ">Rekap</span>
                </a>
            </li>
            <li>
                <a title="User Managemet" class="" href="{{ url('user') }}" aria-expanded="false">
                    <span class="fa fa-id-badge sub-icon-mg" aria-hidden="true"></span>
                    <span class="mini-click-non ">User Management</span>
                </a>
            </li>
        </ul>
    </nav>
</div>

source/resources/views/layouts/sidebar.blade.php
<!-- Start Left menu area -->
<div class="left-sidebar-pro">
    <nav id="sidebar" class="">
        <div class="sidebar-header">
            <a href="{{ url('/') }}"><img class="main-logo" src="{{ asset('assets/img/logo/logo.png') }}" alt="" /></a>
            <strong><a href="{{ url('/') }}"><img src="{{ asset('assets/img/logo/logosn.png') }}" alt="" /></a></strong>
        </div>
        <div class="left-custom-menu-adp-wrap comment-scrollbar">
            <nav class="sidebar-nav left-sidebar-menu-pro">
                <ul class="metismenu" id="menu1">
                @if(Auth::user()->role=="Sekolah")
                    <li>
                        @if(Request::is('home'))
                        <a title="Dashboard" href="{{ url('/') }}" style="background-color:#3498db;color:white">                        
                        @else
                        <a title="Dashboard" href="{{ url('/') }}" style="color:#3498db">                        
                        @endif
                            <span class="fa fa-home sub-icon-mg" aria-hidden="true"></span>
                            <span class="mini-click-non ">Dashboard</span>
                        </a>
                    </li>
                    
                    <li>
                        @if(Request::is('payment'))
                        <a title="Data Pembayaran" class="" href="{{ route('payment.index') }}" aria-expanded="false" style="background-color:#8e44ad;color:white">
                        @elseif(Request::is('payment/*'))
                        <a title="Data Pembayaran" class="" href="{{ route('payment.index') }}" aria-expanded="false" style="background-color:#8e44ad;color:white">
                        @else
                        <a title="Data Pembayaran" class="" href="{{ route('payment.index') }}" aria-expanded="false" style="color:#8e44ad">
                        @endif
                            <span class="fa fa-credit-card sub-icon-mg" aria-hidden="true"></span>
                            <span class="mini-click-non ">Pembayaran</span>
                        </a>
                    </li>
                    <li>
                        @if(Request::is('histori'))
                        <a title="Histori" class="" href="{{ route('history.index') }}" aria-expanded="false" style="background-color:#d35400;color:white">
                        @else
                        <a title="Histori" class="" href="{{ route('history.index') }}" aria-expanded="false" style="color:#d35400;">
                        @endif
                            <span class="educate-icon educate-library icon-wrap" aria-hidden="true"></span>
                            <span class="mini-click-non ">Histori</span>
                        </a>
                    </li>
                    <li>
                        @if(Request::is('income'))
                        <a title="Data Pemasukan" class="" href="{{ route('income.index') }}" aria-expanded="false" style="background-color:#27ae60;color:white">
                        @else
                        <a title="Data Pemasukan" class="" href="{{ route('income.index') }}" aria-expanded="false" style="color:#27ae60;">
                        @endif
                            <span class="educate-icon educate-department sub-icon-mg" aria-hidden="true"></span>
                            <span class="mini-click-non ">Pemasukan</span>
                        </a>
                    </li>
                    <li>
                        @if(Request::is('expense'))
                        <a title="Data Pengeluaran" class="" href="{{ route('expense.index') }}" aria-expanded="false" style="background-color:orange;color:white">
                        @else
                        <a title="Data Pengeluaran" class="" href="{{ route('expense.index') }}" aria-expanded="false" style="color:orange;">
                        @endif
                            <span class="fa fa-tags sub-icon-mg" aria-hidden="true"></span>
                            <span class="mini-click-non ">Pengeluaran</span>
                        </a>
                    </li>
                    <li>
                        @if(Request::is('simpanan'))
                        <a title="Simpanan" class="" href="{{ url('simpanan') }}" aria-expanded="false" style="background-color:#891414;color:white">
                        @else
                        <a title="Simpanan" class="" href="{{ url('simpanan') }}" aria-expanded="false" style="color:#891414;">
                        @endif
                            <span class="fa fa-archive sub-icon-mg" aria-hidden="true"></span>
                            <span class="mini-click-non ">Simpanan</span>
                        </a>
                    </li>
                    <li>
                        @if(Request::is('rekap') || Request::is('rekap_tunggakan') || Request::is('export') || Request::is('rekap_bukbes')|| Request::is('rekap_Pemasukan')|| Request::is('rekap_Pengeluaran'))
                        <a title="Rekapitulasi" class="" href="{{ route('rekap.index') }}" aria-expanded="false" style="background-color:#eb3b5a;color:white">
                        @else
                        <a title="Rekapitulasi" class="" href="{{ route('rekap.index') }}" aria-expanded="false" style="color:#eb3b5a;">
                        @endif
                            <span class="fa fa-files-o sub-icon-mg" aria-hidden="true"></span>
                            <span class="mini-click-non ">Rekap</span>
                        </a>
                    </li>

                    <li>
                        @if(Request::is('setting_biaya'))
                        <a title="Setting Biaya" class="" href="{{ url('setting_biaya') }}" aria-expanded="false" style="background-color:darkcyan;color:white">
                        @else
                        <a title="Setting Biaya" class="" href="{{ url('setting_biaya') }}" aria-expanded="false" style="color:darkcyan;">
                        @endif
                            <span class="fa fa-money sub-icon-mg" aria-hidden="true"></span>
                            <span class="mini-click-non ">Setting Biaya</span>
                        </a>
                    </li>


                    <li>
                        @if(Request::is('user'))
                        <a title="User Managemet" class="" href="{{ url('user') }}" aria-expanded="false" style="background-color:#3498db;color:white">
                        @else
                        <a title="User Managemet" class="" href="{{ url('user') }}" aria-expanded="false" style="color:#3498db;">
                        @endif
                            <span class="fa fa-id-badge sub-icon-mg" aria-hidden="true"></span>
                            <span class="mini-click-non ">User Management</span>
                        </a>
                    </li>
                    <li>
                        @if(Request::is('students'))
                        <a class="has-arrow" title="Data Master" href="#" aria-expanded="false" style="background-color:black;color:white">
                        @elseif(Request::is('majors'))
                        <a class="has-arrow" title="Data Master" href="#" aria-expanded="false" style="background-color:black;color:white">
                        @elseif(Request::is('angkatan'))
                        <a class="has-arrow" title="Data Master" href="#" aria-expanded="false" style="background-color:black;color:white">
                        @elseif(Request::is('financing'))
                        <a class="has-arrow" title="Data Master" href="#" aria-expanded="false" style="background-color:black;color:white">
                        @elseif(Request::is('financing/*'))
                        <a class="has-arrow" title="Data Master" href="#" aria-expanded="false" style="background-color:black;color:white">
                        @elseif(Request::is('angkatan'))
                        <a class="has-arrow" title="Data Master" href="#" aria-expanded="false" style="background-color:black;color:white">
                        @else
                        <a class="has-arrow" title="Data Master" href="#" aria-expanded="false" style="color:black;">
                        @endif
                            <span class="fa fa-diamond sub-icon-mg" aria-hidden="true"></span>
                            <span class="mini-click-non "> Master</span>
                        </a>
                        <ul class="submenu-angle" aria-expanded="false">
                            <li><a title="Data Master Siswa" href="{{ route('students.index') }}"><span class="mini-sub-pro">Siswa</span></a></li>
                            <li><a title="Data Master Jurusan" href="{{ route('majors.index') }}"><span class="mini-sub-pro">Jurusan</span></a></li>
                            <li><a title="Data Master Angkatan" href="{{ route('angkatan.index') }}"><span class="mini-sub-pro">Angkatan</span></a></li>
                            <li><a title="Data Master Kategori Pembiayaan" href="{{ url('financing') }}"><span class="mini-sub-pro">Kategori Pembiayaan</span></a></li>
                        </ul>
                    </li>
                @else

                    <li>
                        <a title="Rekapitulasi" class="" href="{{ route('rekap.index') }}" aria-expanded="false" style="background-color:#eb3b5a;color:white">
                            <span class="fa fa-files-o sub-icon-mg" aria-hidden="true"></span>
                            <span class="mini-click-non ">Rekap</span>
                        </a>
                    </li>
                    <li>
                        @if(Request::is('backpemasukan'))
                        <a class="has-arrow" title="Back Pemasukan" href="#" aria-expanded="false" style="background-color:black;color:white">
                        @elseif(Request::is('backpengeluaran'))
                        <a class="has-arrow" title="Back Pengeluaran" href="#" aria-expanded="false" style="background-color:black;color:white">
                        @elseif(Request::is('backpembayaran'))
                        <a class="has-arrow" title="Back Pembayaran" href="#" aria-expanded="false" style="background-color:black;color:white">
                        @else
                        <a class="has-arrow" title="Back Pemasukan" href="#" aria-expanded="false" style="color:black;">
                        @endif
                            <span class="fa fa-id-badge sub-icon-mg" aria-hidden="true"></span>
                            <span class="mini-click-non ">Controlling</span>
                        </a>
                        <ul class="submenu-angle" aria-expanded="false">
                            <li><a title="Back Pembayaran" href="{{ route('backpembayaran.index') }}"><span class="mini-sub-pro">Backup Pembayaran</span></a></li>
                            <li><a title="Back Pemasukan" href="{{ route('backpemasukan.index') }}"><span class="mini-sub-pro">Backup Pemasukan</span></a></li>
                            <li><a title="Back Pengeluaran" href="{{ route('backpengeluaran.index') }}"><span class="mini-sub-pro">Backup Pengeluaran</span></a></li>
                        </ul>
                    </li>
                @endif
                </ul>
            </nav>
        </div>
    </nav>
</div>
<!-- End Left menu area -->